# This file contains values from Cookiecutter

default_context:
  project_name: "canspirit"
  project_description: "hjghgjhggfhjjghjgvhvhvnbvvvhfch"
  organization: "sig"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "mdvohra"
  email: "mdvohra52@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
